version: "3"

silent: true

tasks:
  check:
    desc: Run all project checks
    cmds:
      - task: "tools:install"
      - task: "go:tidy"
      - task: "test"
      - task: "fmt"
      - task: "lint"

  tools:install:
    cmds:
      - echo '>>> Run install tools'
      - go install github.com/kazhuravlev/toolset/cmd/toolset@latest
      - toolset sync

  go:tidy:
    cmds:
      - echo '>>> Run go get ./...'
      - go get ./...
      - echo '>>> Run go tidy'
      - go mod tidy

  lint:
    desc: Run static analysis
    cmds:
      - echo '>>> Run golangci-lint'
      - toolset run golangci-lint run

  fmt:
    desc: Safe formatting codebase
    cmds:
      - echo ">>> Run Code Formatter"
      - go fmt ./...
      - toolset run gofumpt -l -w .
      - toolset run goimports -l -w .

  test:
    cmds:
      - echo ">>> Go test ./..."
      - go test -v ./...
